### ISSUE TITLE
Soporte firma digital dentro del iso.

### ISSUE THREAD

**Issue by luisza** [leojimenezcr/ubuntu-ucr#12]
En Costa Rica el soporte a firma digital para distribuciones GNU/Linux es malo, poco documentado y tedioso, por lo que sería bueno que esta distribución ya traiga el soporte configurado.

Acá se ha trabajado el tema https://github.com/luisza/instaladoresFirmaDigitalCR , pero lo principal que debería tener es:

1. Descargar los certificados digitales de la CA nacional.
2. Confiar globalmente de ellos para que todos los usuarios confíen de la CA nacional.
3. Configurar el dispositivo PKCS11 con la biblioteca correspondiente e instalando los paquetes necesarios.
4. Configurar Firefox para que reconozca el dispositivo.
5. Hacer trucos para lograr que algunas plataformas nacionales corran bien con soporte a firma (algunas plataformas nacionales necesitan archivos en rutas específicas).

**Comment by valarauco** [comment]
This issue was moved to cslucr/ubuntu-ucr#1
